=== k-ayyy/music-store-system-xml/catalog_19033683.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Author: Kiran Khadka (19033683)
    Date: April 29, 2021
     
    File Name: catalog_19033683.xsd

    File Descriptions: This Schema file is based on the Venetian Blind Design.
                       The layout below, follows the only global declaration for root element, musicStore.
                       The types referencing can be found as below where necessary.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="musicStore"> <!--for musicStore root element-->
        <xs:complexType>
            <xs:sequence>
                <xs:element name="storeInfo" type="storeInfoDataType" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="songInfo" type="songInfoDataType" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="footer" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--closing for root element musicStore-->


    <xs:complexType name="storeInfoDataType">        <!--for child elements inside storeInfo element-->
        <xs:sequence>
            <xs:element name="storeName" type="xs:string"/>
            <xs:element name="storeAddress" type="xs:string"/>
            <xs:element name="storeContact" type="contactDataType" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="storeWebsite" type="xs:anyURI"/>
            <xs:element name="storeLogo" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>   


    <xs:complexType name="contactDataType">        <!--schema for contact datatype-->
        <xs:simpleContent>
            <xs:extension base="xs:string"> <!--for text-->
                <xs:attribute name="contactType" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>  



    <xs:complexType name="songInfoDataType">   <!--schema for songInfo elements-->
        <xs:sequence>
            <xs:element name="song" type="songDataType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>    


    <xs:complexType name="songDataType">       <!--schema for song element-->
        <xs:sequence>
            <xs:element name="imageCover" type="imageCoverDataType"/>
            <xs:element name="songName" type="xs:string"/>
            <xs:element name="singer" type="singerDataType"/>
            <xs:element name="price" type="priceDataType"/>
            <xs:element name="rating" type="xs:string"/>
            <xs:element name="songDescription" type="songDescriptionDataType"/>
        </xs:sequence>
        <xs:attribute name="songID" type="xs:string" use="required"/>
    </xs:complexType>   


    <xs:complexType name="imageCoverDataType">     <!--schema for imageCover element-->
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="coverID" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:complexType name="singerDataType">       <!--for singer element-->
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:complexType name="priceDataType">       <!--for price-->
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="range" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    

    <xs:complexType name="songDescriptionDataType">      <!--for songDescription-->
        <xs:sequence>
            <xs:element name="genre" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="album" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="band" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="writer" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="director" type="xs:string"/>
            <xs:element name="producer" type="xs:string"/>
            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="version" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="recordist" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="releaseDate" type="releaseDateDataType"/>
            <xs:element name="duration" type="xs:string"/>
            <xs:element name="songSummary" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="releaseDateDataType" mixed="true">       <!--for child element referencing of releaseDate-->
        <xs:sequence>
            <xs:element name="year" type="xs:string"/>
            <xs:element name="month" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="day" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== k-ayyy/music-store-system-xml/catalog_19033683.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--xml declaration-->

<!--This XML document contains the data and information on Morning Space Music Store-->
<!--
    Author: Kiran Khadka (19033683)
    Date: April 29, 2021

    File name: catalog_19033683.xml
    Supporting Files: catalog_19033683.dtd | catalog_19033683.xsd | catalog_19033683.css

    Guides: 1) Validate XML document against dtd and schema individually.
            2) To validate this XML doc against dtd file, comment out or remove schema processing instructions.
            3) To validate this XML doc against schema file, comment out or remove the Doctype declaration of 
               external subset of dtd.
            4) For the futher convenience, declaration of root element, <musicStore> is attached in comment 
               after the schema processing instructions.  
            5) There is no need in adding any element declaration in this catalog_19033683.xml file.
            6) For further documentation, follow the comments, where necessary. 

-->


<!DOCTYPE musicStore SYSTEM "catalog_19033683.dtd">
<!--doctype declaration for external subset of dtd-->


<?xml-stylesheet type="text/css" href="catalog_19033683.css"?><!--processing instructions for css-->

<!--schema declaration and linking-->
<musicStore xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="catalog_19033683.xsd">


    <!--<musicStore>-->
    <!-- Uncomment above line root element declaration when needed to validate against dtd.
     There is no need to define element
-->

    <!--Information of the store begins-->
    <storeInfo>
        <storeName>Morning Space Music Store</storeName>
        <storeAddress>Ekantakuna-11, Lalitpur</storeAddress>
        <storeContact contactType="primary">01-239023</storeContact>
        <storeContact contactType="secondary">01-239023</storeContact>
        <storeWebsite>www.morningspacemusic.com</storeWebsite>
        <storeLogo></storeLogo>
    </storeInfo>
    <!--Information of the store finished-->



    <!--Information of songs begins-->
    <songInfo>
        <!--Data 1-->
        <song songID="SO11">
            <imageCover coverID="HB1"></imageCover>
            <songName>Song: Hataarindai, Bataasindai</songName>
            <singer type="single">Vocal: Sajjan Raj Vaidya </singer>
            <price range="low"> Price: NRs. 200</price>
            <rating>MorningSpace Rating: 4.6/5</rating>
            <songDescription>
                <genre>Genre: Nepali Music</genre>
                <writer>Written by: Sajjan Raj Vaidya</writer>
                <director>Directed by: Nurbu Lama</director>
                <producer>Produced by: Sajjan Raj Vaidya</producer>
                <releaseDate>Release Date: 
                    <year>Year: 2019 </year>
                    <month>Month: Jan </month>
                    <day> Day: 02 </day>
                </releaseDate>
                <duration>Duration: 5:41 </duration>
                <songSummary>
                        After a year of great success of Chhithi Bhitra, this 
                        song is expression of the hearts full of unconditional 
                        love &amp; faith.
                </songSummary>
            </songDescription>
        </song>

        <!--Data 2-->
        <song songID="SO12">
            <imageCover coverID="KCH2"></imageCover>
            <songName>Song: K Chha Hajur</songName>
            <singer>Singers: Sachin Pariyar, Asmita Adhikari, Bikram Chhetri </singer>
            <price range="low"> Price: NRs. 200</price>
            <rating>MorningSpace Rating: 4.1/5</rating>
            <songDescription>
                <genre>Genre: Nepali Music</genre>
                <writer>Written by: Netra Aryal</writer>
                <director>Directed by: Kajish Shrestha</director>
                <producer>Produced by: </producer>
                <releaseDate>Release Date: 
                    <year>Year: 2021 </year>
                    <month>Month: Feb </month>
                    <day> Day: 02 </day>
                </releaseDate>
                <duration>Duration: 9:37 </duration>
                <songSummary>
                        K Chha Hajur is a new latest Nepali Lok Dohori 
                        song from viral boy Sachin Pariyar
                </songSummary>
            </songDescription>
        </song>


        <!--Data 3-->
        <song songID="SO13">
            <imageCover coverID="SMLU3"></imageCover>
            <songName>Song: Sunday Morning Love You </songName>
            <singer type="single">Vocal: Bhim Niroula </singer>
            <price range="low">NRs. 100</price>
            <rating>MorningSpace Rating: 3.5/5</rating>
            <songDescription>
                <genre>Genre:Pop </genre>
                <album>Album: Sunday Morning Love You </album>
                <writer>Written by: Bhim Niroula</writer>
                <director>Directed by: Bhim Niroula</director>
                <producer>Produced by:Bhim Niroula</producer>
                <releaseDate>Release Date: 
                    <year>Year: 2013 </year>
                    <month>Month: Oct </month>
                    <day>Day: 12 </day>
                </releaseDate>
                <duration>Duration: 4:45 </duration>
                <songSummary>
                        Bhim Niroula, is an UK based Nepali singer. 
                        The song is written &amp; performed by him for his partner. 
                </songSummary>
            </songDescription>
        </song>



        <!--Data 4-->
        <song songID="SO14">
            <imageCover coverID="SB4"></imageCover>
            <songName>Song: Sangai Bachauna </songName>
            <singer>Vocal: Sareen Deoja </singer>
            <price range="low">Price: NRs. 200</price>
            <rating>MorningSpace Rating: 4/5</rating>
            <songDescription>
                <genre>Genre: Rock Music</genre>
                <album>Album: Monkey Temple </album>
                <band> Band: The Monkey Temple </band>                <!--band is an optional element-->
                <writer>Written by: Sareen Deoja</writer>
                <director>Directed by: Manish Adhikari</director>
                <producer>Produced by: Red Circle</producer>
                <recordist>Recorded by: Bishal Rai </recordist>
                <releaseDate>Release Date:
                    <year>Year: 2017</year>
                    <month>Month: Dec </month>
                    <day>Day: 27 </day>
                </releaseDate>
                <duration>Duration: 5:04</duration>
                <songSummary>
                    Since 1998, the Nepali rocking band has hilarious performance 
                    over the decades. This song dwells on love and relationship with melodious music. 
                </songSummary>
            </songDescription>
        </song>


        <!--Data 5-->
        <song songID="SO15">
            <imageCover coverID="SKM5"></imageCover>
            <songName>Song: Samhalincha Kahile Man</songName>
            <singer type="single">Vocal: Sugam Pokhrel </singer>
            <price range="low">Price: NRs. 150</price>
            <rating>MorningSpace Rating: 4.5/5</rating>
            <songDescription>
                <genre>Genre: Pop Music</genre>
                <album>Album: Sugam Yatra </album>
                <writer>Written by: Suyash Bhattarai  </writer>
                <director>Directed by: Uday Sijapati</director>
                <producer>Produced by: Music.com </producer>
                <releaseDate>Release Date:
                    <year>Year: 2012 </year>
                    <month>Month: Mar </month>
                    <day>Day: 02 </day>
                </releaseDate>
                <duration>Duration: 3:56</duration>
                <songSummary>
                    Evergreen hits of Nepali Pop Singer Sugam Pokhrel, 
                    this song is pure expression of harmonious melodies 
                    in one&apos; life. 
                </songSummary>
            </songDescription>
        </song>


        <!--Data 6-->
        <song songID="SO16">
            <imageCover coverID="M6"></imageCover>
            <songName>Song: Maili</songName>
            <singer>Vocal: Dilli Phombo </singer>
            <price range="high">Price: NRs. 150</price>
            <rating>MorningSpace Rating: 4.5/5</rating>
            <songDescription>
                <genre>Genre: Pop Music</genre>
                <album>Album: Maili</album>
                <band>Band: The Outsiders </band>                <!--optional elements-->
                <writer>Written by: Subigya Sunder Shrestha  </writer>
                <director>Directed by: Subigya Sunder Shrestha</director>
                <producer>Produced by: Rishab Karki</producer>
                <releaseDate>Release Date: 
                    <year>Year: 2012</year>
                    <month>Month: Mar </month>
                    <day>Day: 02 </day>
                </releaseDate>
                <duration>Duration: 3:56</duration>
                <songSummary>
                        Maili is a melodious pop song by the famous band of Nepal: 
                        The Outsider&apos; Band.
                </songSummary>
            </songDescription>
        </song>

        <!--Data 7-->
        <song songID="17">
            <imageCover coverID="TMA7"></imageCover>
            <songName>Song: Take Me to the Alley</songName>
            <singer>Vocal: Gregory Porter</singer>
            <price range="low">Price: NRs. 150</price>
            <rating>MorningSpace Rating: 4/5</rating>
            <songDescription>
                <genre>Genre: Jazz Music</genre>
                <album>Album: Take Me to the Alley</album>
                <writer>Written by: Gregory Porter</writer>
                <director>Directed by: Gregory Porter </director>
